### PR TITLE
Lineups layout page

### LINKED ISSUE #6: Sports

### PR DESCRIPTION
**Pull request by thePeras**
Closes #6 

Please give me your opinion about the design to continue.
The Lineups are swipeable.

Screenshot 2024-08-13 at 18 39 49

Desporto · 6 40pm · 08-13

Screenshot 2024-08-13 at 18 40 03

Desporto

### CODE REVIEW

**Comment by rubuy-74** [comment]
Can you rebase this to make the preview work? Outside of that, the design looks very nice.

**Comment by thePeras** [comment]
I mark this ready so the Netlify preview can exist. But is stills missing connecting to the payload

**Comment by rubuy-74** [comment]
image

The preview is not building because of payload reasons.

**Comment by thePeras** [comment]
> image
> 
> The preview is not building because of payload reasons.

Don't forget to set up the .env with a PAYLOAD_SECRET and POSTGRES_URL

**Comment by rubuy-74** [comment]
So we'll never have a working preview after this PR is merged?

**Comment by thePeras** [comment]
> So we'll never have a working preview after this PR is merged?

Its impossible to use payload in the preveiw because it requires a postgres database. So each page that use payload will no be possible to see I think....

**Comment by rubuy-74** [comment]
> > So we'll never have a working preview after this PR is merged?
> 
> Its impossible to use payload in the preveiw because it requires a postgres database. So each page that use payload will no be possible to see I think....

Yeah, I know that. But its not that the page will be impossible to see, the page will not be able to load/build and will throw an error.
 
Therefore we can't see the preview.

**Comment by thePeras** [comment]
> Yeah, I know that. But its not that the page will be impossible to see, the page will not be able to load/build and will throw an error.
> 
> Therefore we can't see the preview.

I think there is nothing we can do. But I am open to suggestions

**Review by rubuy-74 — CHANGES_REQUESTED** [review]
image

This happens for users without a photo ( the photo is not required in the collection)

**Comment by thePeras** [comment]
>This happens for users without a photo ( the photo is not required in the collection)

Nice catch! Solve it

**Review by rubuy-74 — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
